#!/usr/bin/env bun

const REPO = 'fiestatools/workflowfiesta-cli'

interface Platform {
  variant: string
  envVar: string
}

const PLATFORMS: Platform[] = [
  { variant: 'darwin-arm64', envVar: 'DARWIN_ARM64_SHA256' },
  { variant: 'darwin-x64', envVar: 'DARWIN_X64_SHA256' },
  { variant: 'linux-arm64', envVar: 'LINUX_ARM64_SHA256' },
  { variant: 'linux-x64', envVar: 'LINUX_X64_SHA256' },
]

async function getSha256(
  baseUrl: string,
  version: string,
  variant: string,
  envVar: string,
): Promise<string> {
  const envValue = process.env[envVar]
  if (envValue) {
    return envValue
  }

  const tarballName = `workflowfiesta-${variant}-v${version}.tar.gz`

  // Try to fetch checksums.txt from release
  try {
    const checksumsUrl = `${baseUrl}/checksums.txt`
    const response = await fetch(checksumsUrl)
    if (response.ok) {
      const checksums = await response.text()
      for (const line of checksums.split('\n')) {
        if (line.includes(tarballName)) {
          const sha = line.split(/\s+/)[0]
          if (sha)
            return sha
        }
      }
    }
  }
  catch {
    // Fall through to download method
  }

  // Fallback: download and calculate
  console.error(`Calculating SHA256 for ${tarballName}...`)
  const tarballUrl = `${baseUrl}/${tarballName}`
  const response = await fetch(tarballUrl)
  if (!response.ok) {
    throw new Error(`Failed to download ${tarballUrl}: ${response.status}`)
  }

  const buffer = await response.arrayBuffer()
  const hasher = new Bun.CryptoHasher('sha256')
  hasher.update(new Uint8Array(buffer))
  return hasher.digest('hex')
}

async function main() {
  const args = process.argv.slice(2)

  const [versionArg, outputFile] = args

  if (!versionArg || !outputFile) {
    console.error('Usage: bun run scripts/generate-homebrew-formula.ts <version> <output-file>')
    process.exit(1)
  }

  const version = versionArg.replace(/^v/, '')

  const baseUrl = `https://github.com/${REPO}/releases/download/v${version}`

  console.error(`Generating Homebrew formula for WorkflowFiesta v${version}...`)

  // Get SHA256 checksums for each platform
  const checksums: Record<string, string> = {}

  for (const { variant, envVar } of PLATFORMS) {
    checksums[variant] = await getSha256(baseUrl, version, variant, envVar)
    console.error(`  ${variant}: ${checksums[variant]}`)
  }

  // Generate the formula
  const formula = `# typed: false
# frozen_string_literal: true

# This file is auto-generated. Do not edit manually.
# Generated by: scripts/generate-homebrew-formula.ts

class Workflowfiesta < Formula
  desc "Terminal interface for WorkflowFiesta AI agents"
  homepage "https://github.com/${REPO}"
  version "${version}"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "${baseUrl}/workflowfiesta-darwin-arm64-v${version}.tar.gz"
      sha256 "${checksums['darwin-arm64']}"
    else
      url "${baseUrl}/workflowfiesta-darwin-x64-v${version}.tar.gz"
      sha256 "${checksums['darwin-x64']}"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "${baseUrl}/workflowfiesta-linux-arm64-v${version}.tar.gz"
      sha256 "${checksums['linux-arm64']}"
    else
      url "${baseUrl}/workflowfiesta-linux-x64-v${version}.tar.gz"
      sha256 "${checksums['linux-x64']}"
    end
  end

  def install
    bin.install "wf"
    # Create workflowfiesta symlink
    bin.install_symlink "wf" => "workflowfiesta"
  end

  test do
    assert_match version.to_s, shell_output("\#{bin}/wf --version")
  end
end
`

  await Bun.write(outputFile, formula)
  console.error(`Formula written to: ${outputFile}`)
}

main().catch((err) => {
  console.error(err)
  process.exit(1)
})
